services:
  db:
    image: mysql:8.0
    container_name: realestate-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: realty_db
      MYSQL_ROOT_PASSWORD: qnehdtks1!
      MYSQL_USER: realestate
      MYSQL_PASSWORD: qnehdtks1!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 300M

  app:
    # 핵심: build: . 대신 Docker Hub에 올라갈 이미지 이름을 사용합니다.
    image: ktjone/realestate-app
    container_name: realestate-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # DB 주소를 'db'로 설정하여 컨테이너 간 통신 가능하게 함
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/realty_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: realestate
      SPRING_DATASOURCE_PASSWORD: qnehdtks1!
    deploy:
      resources:
        limits:
          memory: 500M