services:
  db:
    image: mysql:8.0
    container_name: realestate-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: realty_db
      MYSQL_ROOT_PASSWORD: qnehdtks1!
      # 사용자 계정 설정
      MYSQL_USER: realestate               # 본인이 원하는 아이디로 수정 가능
      MYSQL_PASSWORD: qnehdtks1!
    ports:
      - "3308:3306"                 # 내 컴퓨터 3308 -> 도커 3306 연결
    volumes:
      - ./mysql_data:/var/lib/mysql