server.port=8081

spring.application.name=realestate

# DB ?? ?? (3307 ?? + ?? ??)
spring.datasource.url=jdbc:mysql://localhost:3308/realty_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=realestate
spring.datasource.password=qnehdtks1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ?? (??? ?? ??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect