spring.application.name=realestate
# DB ?? ?? (Docker MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/realty_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=qnehdtks1!

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true